import { describe, expect, test } from "bun:test"

const root = new URL("../../../", import.meta.url)
const layout = await Bun.file(new URL("app/src/pages/layout-new.tsx", root)).text()
const titlebar = await Bun.file(new URL("app/src/components/titlebar.tsx", root)).text()
const desktop = await Bun.file(new URL("desktop/src/renderer/index.tsx", root)).text()
const workspace = await Bun.file(new URL("desktop/src/renderer/esg-workbench.tsx", root)).text()
const styles = await Bun.file(new URL("desktop/src/renderer/esg-workbench.css", root)).text()

// Structural regression guards, not a replacement for real desktop interaction tests.
describe("ESG native host integration structure", () => {
  test("native titlebar remains outside and above the optional main workspace", () => {
    expect(layout.indexOf("<Titlebar")).toBeLessThan(layout.indexOf("<main"))
    expect(layout.indexOf("<main")).toBeLessThan(layout.indexOf("component={workspace().component}"))
    expect(layout).toContain("fallback={<Suspense>{props.children}</Suspense>}")
  })
  test("entry is placed inside native navigation without replacing native tabs", () => {
    expect(titlebar).toContain("{props.workspace?.entry}")
    expect(titlebar).toContain("<TitlebarTabStrip")
    expect(titlebar).toContain("props.workspace?.onNativeNavigate()")
    expect(titlebar).toContain("workspaceActive")
  })
  test("desktop app is no longer a child of the ESG outer shell", () => {
    expect(desktop).not.toContain("<ESGWorkbench directory={config.directory}><App />")
    expect(desktop).toContain("component: Workbench")
    expect(workspace).not.toContain("esg-host-nav")
    expect(workspace).not.toContain("OpenCode 原生会话</button>")
  })
  test("business and native panes stay mounted and discussions request split view", () => {
    expect(workspace).toContain('pending: context, pane: "split"')
    expect(workspace).toContain('hidden={state.pane === "session"}')
    expect(workspace).toContain('hidden={state.pane === "esg"}')
    expect(workspace).toContain('<div class="esg-native-content">{props.children}</div>')
    expect(workspace).toContain("tabs.newDraft")
    expect(workspace).not.toContain("session.prompt(")
  })
  test("all embedded modes adapt the new draft without touching full-page routes or timelines", () => {
    expect(styles).toContain("container-name:esg-conversation")
    expect(styles).not.toContain("max-height:600px")
    expect(styles).toContain('.esg-workspace[data-view=split] [data-component="session-new-design"]')
    expect(styles).toContain("position:relative;top:auto;flex:1 0 auto;")
    expect(styles).toContain("max-width:none;min-width:0;display:flex")
    expect(styles).toContain("max-height:none;min-height:60px;height:100%")
  })
  test("both orientations are explicit preferences, not overridden by window width", () => {
    expect(workspace).toContain("data-layout={preferences.layout}")
    expect(workspace).toContain('aria-label="工作台与会话布局"')
    expect(workspace).toContain('aria-pressed={preferences.layout === "side-by-side"}')
    expect(workspace).toContain('aria-pressed={preferences.layout === "stacked"}')
    expect(workspace).toContain("readESGLayout(() => window.localStorage)")
    expect(styles).toContain("[data-layout=side-by-side]")
    expect(styles).toContain("[data-layout=stacked]")
    expect(styles.split("@media(max-width:1500px)")[1]?.split("\n")[0]).not.toContain("grid-template")
  })
  test("floating repositions the same native pane and offers drag, resize and redocking", () => {
    expect(workspace.match(/class="esg-native-pane"/g)).toHaveLength(1)
    expect(workspace).toContain('aria-pressed={preferences.layout === "floating"}')
    expect(workspace).toContain('aria-label="移动会话浮窗"')
    expect(workspace).toContain('aria-label="调整会话浮窗大小"')
    expect(workspace).toContain("setPointerCapture")
    expect(workspace).toContain("new ResizeObserver")
    expect(workspace).not.toContain("window.open(")
    expect(styles).toContain("[data-layout=floating] .esg-native-pane{position:absolute")
    expect(styles).toContain("[data-floating-interaction=true] iframe{pointer-events:none}")
    expect(styles).toContain('[data-view=split] [data-component="session-new-design"]>div:first-child>div>svg{display:none}')
    expect(styles).toContain('[data-component="session-new-design"]>.pointer-events-none{display:none}')
  })
  test("workspace controls are expandable, in flow and clear of the resize grip", () => {
    expect(workspace).toContain('aria-expanded={preferences.environment}')
    expect(workspace).toContain('data-environment={preferences.environment}')
    expect(styles).toContain('[data-environment=true] [data-component="session-new-design"] .mt-8>.min-h-7{display:flex;flex-direction:row;flex-wrap:wrap;flex-shrink:0;')
    expect(styles).toContain('padding:3px 36px 5px 12px')
    expect(styles).toContain('.mt-8>div:first-child{flex:1;min-height:112px}')
    expect(workspace).toContain('contextIdentity(context()).title')
    expect(workspace).toContain('contextIdentity(context()).report')
  })
})
